### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by SomeoneAwefull** [SkyrimTogether/issues-launcher#15]
## Description
When i am on the Harbor launcher and i click login i get a message that says that I don't have access to the beta, so i look on the website and i log in with the same account and it says that i'm a patron.
How to reproduce this issue:
i run the launcher and click login 
1. Start the launcher.
2. Connect login.
3. Fail to login.
## Reproduction rate
every time i click login
## Expected result
to log in
* Launcher version:
    * The Elder Scrolls V: Skyrim Special Edition
    * Windows 10 x64

**Comment by Rhicat** [comment]
Hi! I had this happen to me a few times. What solved it for me was going onto Patreon and making sure my Skyrim Together account and Patreon were linked. Then I went onto Skyrim Together's website and made sure I was logged in there as well, and that it said I was a Patreon. Those steps seem to have solved my problem outright, and I haven't had any problems like that since. I think Patreon logged me out once or twice, and that is what caused the confusion between accounts. Good luck!

**Comment by DeltaxHawk** [comment]
Any other way to fix? having the same issue.

**Comment by Pokang** [comment]
Logout and relogin from our website.

**Comment by DeltaxHawk** [comment]
ive done that, relogged into patreon, restarted launcher.... all dont fix. keeps telling me i dont have access to closed beta.

**Comment by Pokang** [comment]
Do you have the golden border on the top right that says how much you've pledged on our website?

**Comment by DeltaxHawk** [comment]
i do now, had to relogin like 5 times

**Comment by therodfather** [comment]
Having this same issue. Website shows my pledge, logged out of website and in multiple times, and made sure my patreon was connected. Not sure where to go from here :(

**Comment by Pokang** [comment]
@therodfather As specified on our Patreon, Reddit, Discord, and Twitter accounts, the closed beta has ended.

**Comment by therodfather** [comment]
Ah I don't use twitter, discord, or reddit so I guess I must have missed it. It be useful to send an email or put it on the website front page area.

**Comment by Pokang** [comment]
The website is the only thing that we have yet to update, yes. Sorry for the inconvenience, have a great day!
