### ISSUE TITLE
Hitting 'Play' opens the Skyrim Launcher

### ISSUE THREAD

**Issue by Pistrie** [SkyrimTogether/issues-launcher#25]
## Description

When I click play it opens the Skyrim Launcher without actually doing anything from there.
https://youtu.be/WPbSkOSjfZI

## Steps to reproduce

How to reproduce this issue:

1. Start the launcher.
2. Hit play.
3. Somehow have it open the Skyrim Launcher.

## Reproduction rate

Everytime I press play

## Expected result

It directly opens the game.

## Your environment

* Launcher version: 1.0.5

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition

* Operating system (choose one):
    * Windows 10 x64

## Evidence (optional)

https://youtu.be/WPbSkOSjfZI

## Final checks for the reporter

- [ x ] I have browsed through the other issues and confirmed that this issue has not been reported already
- [ x ] I made sure that I have applied the template for my bug report

**Comment by Pokang** [comment]
Could you please try launching Harbor as administrator and let me know if that still happens?

**Comment by Pistrie** [comment]
Launching as administrator did the trick, but I have another problem now. I tried to launch it through MO2 to get the mods to load, and then it said that Engine Fixes was an outdated run time or something like that, so I tried updating the mod but that didnt fix it, so I disabled it for the time being. But when I launch it through MO2, this happens: -> https://youtu.be/546ojFd92MQ

**Comment by Pokang** [comment]
Engine fixes, if I remember correctly, modified the binary files of Skyrim, which prevents our mod from launching. That said, it should throw a pattern error in the console. Try without mods first and see if you can get it to work.
Since the binary file was modified, you will probably have to do a clean reinstall.

**Comment by Pistrie** [comment]
Okay so I removed any files I had to manually install with EngineFixes and had Steam validate my files. Everything seemed to be fine as nothing needed to be redownloaded but I stall have the same problem

**Comment by Pokang** [comment]
How about when not launching through MO2?

**Comment by Pistrie** [comment]
That still works, but if I do it that way none of my mods get loaded

**Comment by thmsndk** [comment]
Just to chime in @Pistrie , i'm running the latest skyrim SE from steam, latest MO2 (2.2.0), latest version of SSE Engine fixes (4.4) and a couple of other mods, and i'm launching skyrim fine, I did however experience crashes due to some of my mods not being updated to the latest SKSE version / runtime but once I disabled, or updated them, everything was starting up as it should :)

**Comment by WopsS** [comment]
Do you have the game installed in `C:/Program Files`?

**Comment by Pistrie** [comment]
It's `C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition`

**Comment by Pistrie** [comment]
Okay a little update.

Even though I updated my Skyrim yesterday (I postponed it until I knew for sure that all my .dll mods were updated) SKSE says that my current Skyrim version is not up to date. At the moment Im validating my files to make sure everything is okay

**Comment by Pistrie** [comment]
Okay I just reinstalled Skyrim to be 200% sure that everything was up to date, and now it's working
